[default]
# Model Information.
d_model = "DLinear"
d_model_input_type = "x_only"
m_individual = 1 # Allows each feature to have its own Linear Layer.


# -------------------------
# Datasets
# -------------------------
[[runs]]
d_seq_len = 336
d_pred_len = 48
d_test_stride = 48


[[runs]]
d_seq_len = 336
d_pred_len = 96
d_test_stride = 48



[[runs]]
d_seq_len = 336
d_pred_len = 192
d_test_stride = 192


[[runs]]
d_seq_len = 336
d_pred_len = 336
d_test_stride = 336


[[runs]]
d_seq_len = 336
d_pred_len = 512
d_test_stride = 512


[[runs]]
d_seq_len = 336
d_pred_len = 720
d_test_stride = 720


