[default]
# Model
d_model = "iTransformer"
d_model_input_type = "x_mark_dec_incld"

# Other params
m_e_layers = 2
m_n_heads = 8
m_d_model = 256
m_d_ff = 256
m_dropout = 0.05
m_fc_dropout = 0.3
m_use_norm = true
m_embed = "timeF"
m_class_strategy = "projection"
m_factor = 1
m_activation = "gelu"


# -------------------------
# Runs
# -------------------------
[[runs]]
d_seq_len = 336
d_pred_len = 48

[[runs]]
d_seq_len = 336
d_pred_len = 96

[[runs]]
d_seq_len = 336
d_pred_len = 192

[[runs]]
d_seq_len = 336
d_pred_len = 336
m_d_model = 512
m_d_ff = 512

[[runs]]
d_seq_len = 336
d_pred_len = 512
m_d_model = 512
m_d_ff = 512

[[runs]]
d_seq_len = 336
d_pred_len = 720
m_d_model = 512
m_d_ff = 512