[default]
d_model = "HaDAM"
d_model_input_type = "x_only"
d_auxillary_loss = true
m_revin_affine = true
m_revin_subtract_last = false
m_patch_size = 8          # must divide seq_len (336 % 16 == 0)
m_patch_dim = 128            # intra-patch embedding dimension
m_n_layers = 1
m_attn_head_kernel_size = 32
m_attn_head_dropout = 0.2
m_dropout = 0.2


[[runs]]
d_seq_len = 336
d_pred_len = 48
d_test_stride = 48


[[runs]]
d_seq_len = 336
d_pred_len = 96
d_test_stride = 96


[[runs]]
d_seq_len = 336
d_pred_len = 192
d_test_stride = 192

[[runs]]
d_seq_len = 336
d_pred_len = 336
d_test_stride = 336


[[runs]]
d_seq_len = 336
d_pred_len = 512
d_test_stride = 512


[[runs]]
d_seq_len = 336
d_pred_len = 720
d_test_stride = 720
